# https://aka.ms/yaml

trigger:
- main

pr:
- main

variables:
  DotNetVersion: 5.0.100-rc.2.20480.7

jobs:
- job: windows
  pool:
    vmImage: windows-latest
  variables:
    LogDirectory: $(Build.ArtifactStagingDirectory)\logs
  steps:
    - powershell: |
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
        & .\dotnet-install.ps1 -Version $(DotNetVersion) -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
        & dotnet --list-sdks
      displayName: install .NET $(DotNetVersion)
      errorActionPreference: stop

    - powershell: |
        & dotnet build HelloAndroid\HelloAndroid.csproj -c Debug -bl:$(LogDirectory)\Debug-HelloAndroid.binlog
        & dotnet build HelloAndroid\HelloAndroid.csproj -c Release -bl:$(LogDirectory)\Release-HelloAndroid.binlog
        & dotnet build HelloForms.Droid\HelloForms.Droid.csproj -c Debug -bl:$(LogDirectory)\Debug-HelloForms.binlog
        & dotnet build HelloForms.Droid\HelloForms.Droid.csproj -c Release -bl:$(LogDirectory)\Release-HelloForms.binlog
      displayName: build samples
      errorActionPreference: stop

    - task: CopyFiles@2
      displayName: copy artifacts
      inputs:
        contents: '*Android\**\*-Signed.apk'
        targetFolder: $(Build.ArtifactStagingDirectory)
        overWrite: true
      condition: always()

    - task: PublishPipelineArtifact@1
      displayName: publish artifacts
      inputs:
        artifactName: windows-artifacts
        targetPath: $(Build.ArtifactStagingDirectory)
      condition: always()

- job: mac
  timeoutInMinutes: 120
  pool:
    vmImage: macOS-latest
  variables:
    - group: xamops-azdev-secrets
    - name: LogDirectory
      value: $(Build.ArtifactStagingDirectory)/logs
  steps:
    - bash: >
        curl -L https://dot.net/v1/dotnet-install.sh > dotnet-install.sh &&
        sh dotnet-install.sh --version $(DotNetVersion) --install-dir ~/.dotnet/ --verbose &&
        dotnet --list-sdks
      displayName: install .NET $(DotNetVersion)

    - task: provisionator@2
      displayName: install Xcode
      inputs:
        github_token: $(github-pat)
        provisioning_script: $(System.DefaultWorkingDirectory)/scripts/provision.csx
        provisioning_extra_args: '-v -v -v -v'

    - bash: |
        set -x
        mkdir -p ~/Library/Preferences/Xamarin
        /usr/libexec/PlistBuddy -c "add :AppleSdkRoot string $(dirname $(dirname $(xcode-select -p)))" ~/Library/Preferences/Xamarin/Settings.plist
      displayName: configure vsmac xcode

    - bash: |
        dotnet build net6-samples.sln -c Debug -bl:$(LogDirectory)/Debug.binlog &&
        dotnet build net6-samples.sln -c Release -bl:$(LogDirectory)/Release.binlog
      displayName: build samples

    - task: CopyFiles@2
      displayName: copy artifacts
      inputs:
        contents: |
          *Android/**/*-Signed.apk
          *iOS/**/*.app/**
        targetFolder: $(Build.ArtifactStagingDirectory)
        overWrite: true
      condition: always()

    - task: PublishPipelineArtifact@1
      displayName: publish artifacts
      inputs:
        artifactName: mac-artifacts
        targetPath: $(Build.ArtifactStagingDirectory)
      condition: always()
