# https://aka.ms/yaml

trigger:
- main
- develop

pr:
- main
- develop

variables:
  DotNetVersion: 6.0.100-preview.2.21114.3
  DotNet.Cli.Telemetry.OptOut: true
  Android.Msi: https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4498522/master/2f83bddb99f6a0948631cd0f09bf037ba8a4e359/Microsoft.NET.Workload.Android.11.0.200.118.msi
  Android.Pkg: https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4498522/master/2f83bddb99f6a0948631cd0f09bf037ba8a4e359/Microsoft.NET.Workload.Android-11.0.200-ci.master.118.pkg
  iOS.Msi: https://bosstoragemirror.azureedge.net/wrench/main/3a69beae5337a1dba3dd2b56c442a6b5ec089429/4505964/package/Microsoft.NET.Workload.iOS.14.4.100-ci.main.1144.msi
  iOS.Pkg: https://bosstoragemirror.azureedge.net/wrench/main/3a69beae5337a1dba3dd2b56c442a6b5ec089429/4505964/package/Microsoft.iOS.Bundle.14.4.100-ci.main.1144.pkg

jobs:
- job: windows
  pool:
    vmImage: windows-latest
  variables:
    LogDirectory: $(Build.ArtifactStagingDirectory)\logs
  steps:
    - powershell: |
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
        & .\dotnet-install.ps1 -Version $(DotNetVersion) -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
        & dotnet --list-sdks
      displayName: install .NET $(DotNetVersion)
      errorActionPreference: stop

    - powershell: |
        & dotnet tool install --global boots
        & boots $(Android.Msi)
        & boots $(iOS.Msi)
      displayName: install .NET workloads
      errorActionPreference: stop

    - powershell: |
        & dotnet build net6-samples.sln -c Debug   -bl:$(LogDirectory)\Debug.binlog
        & dotnet build net6-samples.sln -c Release -bl:$(LogDirectory)\Release.binlog
      displayName: build samples
      errorActionPreference: stop

    - task: CopyFiles@2
      displayName: copy artifacts
      inputs:
        contents: '*Android\**\*-Signed.apk'
        targetFolder: $(Build.ArtifactStagingDirectory)
        overWrite: true
      condition: always()

    - task: PublishPipelineArtifact@1
      displayName: publish artifacts
      inputs:
        artifactName: windows-artifacts
        targetPath: $(Build.ArtifactStagingDirectory)
      condition: always()

- job: mac
  timeoutInMinutes: 120
  pool:
    vmImage: macOS-latest
  variables:
    - name: LogDirectory
      value: $(Build.ArtifactStagingDirectory)/logs
    - name: DotNet.Root
      value: /usr/local/share/dotnet/
    - name: DotNet.Tools
      value: ~/.dotnet/tools
  steps:
    - task: UseDotNet@2
      displayName: install .NET Core 3.1
      inputs:
        version: 3.1.x
        installationPath: $(DotNet.Root)

    - bash: >
        export PATH="$(DotNet.Root):$(DotNet.Tools):$PATH" &&
        curl -L https://raw.githubusercontent.com/dotnet/install-scripts/7a9d5dcab92cf131fc2d8977052f8c2c2d540e22/src/dotnet-install.sh > dotnet-install.sh &&
        sh dotnet-install.sh --version $(DotNetVersion) --install-dir $DOTNET_ROOT --verbose &&
        dotnet --list-sdks &&
        echo "##vso[task.setvariable variable=PATH]$PATH"
      displayName: install .NET $(DotNetVersion)

    - bash: |
        dotnet tool install --global boots
        boots $(Android.Pkg)
        boots $(iOS.Pkg)
      displayName: install .NET workloads

    - bash: sudo xcode-select -s /Applications/Xcode_12.4.app
      displayName: select Xcode 12.4

    - bash: |
        set -x
        mkdir -p ~/Library/Preferences/Xamarin
        rm -f ~/Library/Preferences/Xamarin/Settings.plist
        /usr/libexec/PlistBuddy -c "add :AppleSdkRoot string $(dirname $(dirname $(xcode-select -p)))" ~/Library/Preferences/Xamarin/Settings.plist || true
        cat ~/Library/Preferences/Xamarin/Settings.plist || true
      displayName: configure vsmac xcode

    - bash: |
        dotnet build net6-samples.sln -c Debug   -bl:$(LogDirectory)/Debug.binlog &&
        dotnet build net6-samples.sln -c Release -bl:$(LogDirectory)/Release.binlog
      displayName: build samples

    - task: CopyFiles@2
      displayName: copy artifacts
      inputs:
        contents: |
          *Android/**/*-Signed.apk
          *iOS/**/*.app/**
        targetFolder: $(Build.ArtifactStagingDirectory)
        overWrite: true
      condition: always()

    - task: PublishPipelineArtifact@1
      displayName: publish artifacts
      inputs:
        artifactName: mac-artifacts
        targetPath: $(Build.ArtifactStagingDirectory)
      condition: always()
